version: '3.3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:senha-mysql@db:3306/cad_merenda
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'cad_merenda'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'senha-mysql'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'senha-mysql'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
# Names our volume
volumes:
  my-db:
